# Generated by Django 5.2.7 on 2025-10-31 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('ventas', 'Ventas'), ('clientes', 'Clientes'), ('productos', 'Productos'), ('ia', 'IA')], max_length=30)),
                ('formato', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON')], default='CSV', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_texto', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='reporting.reporte')),
            ],
        ),
    ]
