# Generated by Django 5.2.7 on 2025-10-31 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='customers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cart.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_carritos', to='catalog.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('cliente',), name='uniq_carrito_activo_por_cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
