"""
Django settings for SmartSalesBackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from decouple import config, Csv
from datetime import timedelta  # <-- CORRECCIÓN 1: Añadido

BASE_DIR = Path(__file__).resolve().parent.parent

# --- Seguridad y entorno ---
SECRET_KEY = config('SECRET_KEY', default='CHANGE_ME')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

AUTH_USER_MODEL = 'accounts.User'

# --- Apps instaladas ---
INSTALLED_APPS = [
     # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     # Complementarios 
    'rest_framework',
    'rest_framework_simplejwt',  # <-- CORRECCIÓN 2: Añadido
    'rest_framework_simplejwt.token_blacklist', # <-- CORRECCIÓN 3: Añadido
    'django_filters',
    'drf_spectacular',
    'corsheaders',

     # apps que vamos creando para el proyecto

    'apps.accounts',
    'apps.catalog',
    'apps.customers',
    'apps.cart',
    'apps.sales',
    'apps.marketing',
    'apps.security',
    'apps.reporting',
]

# --- Middleware (CORS debe ir arriba del common) ---
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.security.middleware.AuditMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartSalesBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # si luego usas templates, agrega rutas aquí
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartSalesBackend.wsgi.application'

# --- Base de datos (PostgreSQL desde .env) ---
DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('PG_NAME'),
        'USER': config('PG_USER'),
        'PASSWORD': config('PG_PASS'),
        'HOST': config('PG_HOST'),
        'PORT': config('PG_PORT', cast=int),
    }
}

# --- Password validators ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internacionalización ---
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/La_Paz'
USE_I18N = True
USE_TZ = True

# --- Archivos estáticos y media ---
STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- DRF + JWT + Filters ---
REST_FRAMEWORK = {
 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
 'DEFAULT_AUTHENTICATION_CLASSES': (
 'rest_framework_simplejwt.authentication.JWTAuthentication',
 ),
'DEFAULT_PERMISSION_CLASSES': (
 'rest_framework.permissions.AllowAny',
 ),
'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
'PAGE_SIZE': 20,
}

# --- CORRECCIÓN 4: Añadida la configuración de Simple JWT ---
SIMPLE_JWT = {
    # Tiempos de vida (5 min para acceso, 1 día para refresco)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    
    # Rotación de tokens (mejora la seguridad)
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True, # Invalida el token de refresco anterior

    # Configuración de Cabeceras
    "AUTH_HEADER_TYPES": ("Bearer",), # Acepta "Bearer <token>"
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",

    # Algoritmo
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY, # Usa la SECRET_KEY principal
}


# --- OpenAPI / Swagger ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'SmartSales365 API',
    'DESCRIPTION': 'Backend de SmartSales365 (Django + DRF + JWT).',
    'VERSION': '1.0.0',
}

# --- CORS para el front ---
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv(), default='http://localhost:3000')
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=False, cast=bool)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv(), default='')

# --- ¡AÑADIR ESTAS LÍNEAS! ---
# Define la URL base para acceder a los archivos subidos (ej. /media/productos/mi-foto.jpg)
MEDIA_URL = '/media/'
# Define la carpeta en tu disco duro donde se guardarán los archivos
MEDIA_ROOT = BASE_DIR / 'media'